//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topscholars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        public int AssignmentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
