//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topscholars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public byte[] Document { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
