//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topscholars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees
    {
        public int FeeId { get; set; }
        public int StudentId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
